import { expect, test } from '@playwright/test';
import type { Page } from '@playwright/test';
import type { Claim, GraphData, QuestionRequest, QuestionResult } from '../../src/types';

const headers = { Authorization: 'Bearer synthetic-browser-token' };
const primary = '验收新增人工记录项目';
const secondary = '验收新增人工记录项目二';

async function openQuestion(page: Page, project = primary) {
  await page.goto('/#token=synthetic-browser-token');
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: project });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await expect(dialog).toContainText(project);
  return dialog;
}

test('真实人工问题保存原文、未知范围、图与证据，追加修改不丢旧记录', async ({ page, request }) => {
  const dialog = await openQuestion(page);
  const text = '  合成人工问题：未知范围如何复核？\n第二行保留空白。  ';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(text);
  await page.screenshot({ path: '../.cache/frontend-manual-question-desktop.png' });
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  const response = await responsePromise;
  expect(response.status()).toBe(200);
  const body: QuestionRequest = response.request().postDataJSON();
  const saved: QuestionResult = await response.json();
  expect(body).toMatchObject({ text, scope: null, actor: 'human:本机用户' });
  expect(saved.replayed).toBe(false);
  const detail = page.getByRole('dialog', { name: `记录 ${saved.claim_id} 详情`, exact: true });
  await expect(detail).toContainText('人工确认');
  await expect(detail).toContainText('范围未知');
  const original: Claim = (await (await request.get(`/api/claims/${saved.claim_id}`, { headers })).json()).claim;
  expect(original).toMatchObject({ scope: null, basis: 'manual', actor: 'human:本机用户', claim_state: 'confirmed', effective_state: 'confirmed', confirmation_source: 'human', payload: { kind: 'question', content: text } });
  expect(original.evidence.map(span => span.event_id)).toContain(saved.event_id);
  const graph: GraphData = await (await request.get(`/api/graph?project=${body.project_id}`, { headers })).json();
  expect(graph.claims.some(item => item.claim_id === saved.claim_id)).toBe(true);
  await expect(page.locator('.question-index')).toContainText('未知范围如何复核');
  await detail.locator('.evidence-link').first().click();
  const quote = page.getByTestId('evidence-quote');
  await expect(quote).toBeVisible();
  const rawQuote = await quote.textContent() ?? '';
  expect(JSON.parse('"' + rawQuote + '"')).toBe(text);
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(rawQuote));
  expect(Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, '0')).join('')).toBe(original.evidence[0].quote_sha256);
  await page.getByRole('button', { name: '关闭原文', exact: true }).click();
  await detail.getByRole('button', { name: '修改', exact: true }).click();
  const edit = page.getByRole('dialog', { name: '保留原文，追加你的判断', exact: true });
  await expect(edit.getByLabel('研究范围（可留空）', { exact: true })).toHaveValue('');
  await edit.getByLabel('内容', { exact: true }).fill(`${text}\n人工追加说明。`);
  const editResponsePromise = page.waitForResponse(response => response.url().endsWith(`/api/claims/${saved.claim_id}/edit`));
  await edit.getByRole('button', { name: '修改并确认', exact: true }).click();
  const editedResponse = await editResponsePromise;
  expect(editedResponse.status()).toBe(200);
  expect(editedResponse.request().postDataJSON().scope).toBeNull();
  const edited = await editedResponse.json();
  const replacement: Claim = (await (await request.get(`/api/claims/${edited.claim_id}`, { headers })).json()).claim;
  expect(replacement).toMatchObject({ scope: null, replaces_claim: saved.claim_id, basis: 'manual', effective_state: 'confirmed' });
  expect(replacement.evidence).toEqual(original.evidence);
  const previous: Claim = (await (await request.get(`/api/claims/${saved.claim_id}`, { headers })).json()).claim;
  expect(previous.payload.content).toBe(text);
  expect(previous.replacement_ids).toContain(edited.claim_id);
  await expect(page.getByRole('dialog', { name: `记录 ${edited.claim_id} 详情`, exact: true })).toContainText('人工修改前后');
});

test('已写入但响应丢失后同意图重试找回原记录，忙时不会重复提交', async ({ page, request }) => {
  const bodies: QuestionRequest[] = [];
  const firstSaved: QuestionResult[] = [];
  let release!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/records/question', async route => {
    bodies.push(route.request().postDataJSON());
    const response = await route.fetch();
    if (bodies.length === 1) {
      firstSaved.push(await response.json());
      await held;
      await route.abort('failed');
    } else await route.fulfill({ response });
  });
  const dialog = await openQuestion(page);
  const text = '合成响应丢失后找回同一问题';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(text);
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '正在保存…', exact: true })).toBeDisabled();
  await dialog.locator('form').dispatchEvent('submit');
  await expect.poll(() => firstSaved.length).toBe(1);
  expect(bodies).toHaveLength(1);
  release();
  await expect(dialog.getByRole('alert')).toBeVisible();
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue(text);
  const retryPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  const retry: QuestionResult = await (await retryPromise).json();
  expect(retry.replayed).toBe(true);
  expect(retry.claim_id).toBe(firstSaved[0].claim_id);
  expect(bodies).toHaveLength(2);
  expect(bodies[1].request_id).toBe(bodies[0].request_id);
  const graph: GraphData = await (await request.get(`/api/graph?project=${bodies[0].project_id}`, { headers })).json();
  expect(graph.claims.filter(item => item.payload.content === text)).toHaveLength(1);
  await expect(page.getByRole('dialog', { name: `记录 ${retry.claim_id} 详情`, exact: true })).toBeVisible();
});

test('真实409保留草稿和意图，刷新后仍须人工提交', async ({ page, request }) => {
  const bodies: QuestionRequest[] = [];
  await page.route('**/api/records/question', async route => { bodies.push(route.request().postDataJSON()); await route.continue(); });
  const dialog = await openQuestion(page);
  const projectId = await page.getByLabel('当前项目', { exact: true }).inputValue();
  const graph: GraphData = await (await request.get(`/api/graph?project=${projectId}`, { headers })).json();
  const parallel = await request.post('/api/records/question', { headers, data: { project_id: projectId, text: '另一窗口的合成人工问题', scope: null, actor: 'human:另一窗口', request_id: crypto.randomUUID(), expected_revision: graph.revision } });
  expect(parallel.status()).toBe(200);
  const text = '合成版本冲突后由用户重新提交';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(text);
  const rejectedPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  expect((await rejectedPromise).status()).toBe(409);
  await expect(dialog.getByRole('button', { name: '保存研究问题', exact: true })).toBeDisabled();
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue(text);
  await dialog.getByRole('button', { name: '读取最新版本', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '保存研究问题', exact: true })).toBeEnabled();
  expect(bodies).toHaveLength(1);
  const updated: GraphData = await (await request.get(`/api/graph?project=${projectId}`, { headers })).json();
  expect(updated.claims.filter(item => item.payload.content === text)).toHaveLength(0);
  const savedPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  expect((await savedPromise).status()).toBe(200);
  expect(bodies).toHaveLength(2);
  expect(bodies[1].request_id).toBe(bodies[0].request_id);
  expect(bodies[1].expected_revision).toBeGreaterThan(bodies[0].expected_revision);
});

test('失败草稿按项目隔离，已知范围和小屏保存归属正确', async ({ page, request }) => {
  const bodies: QuestionRequest[] = [];
  await page.route('**/api/records/question', async route => {
    bodies.push(route.request().postDataJSON());
    if (bodies.length === 1) await route.fulfill({ status: 503, json: { error: '合成临时写入故障' } });
    else await route.continue();
  });
  let dialog = await openQuestion(page);
  const firstText = '合成第一项目的保留草稿';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(firstText);
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  await dialog.getByRole('button', { name: '关闭新增问题', exact: true }).click();
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: secondary });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue('');
  await page.setViewportSize({ width: 390, height: 844 });
  const secondText = '合成第二项目的小屏人工问题';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(secondText);
  await dialog.getByLabel('研究范围（可留空）', { exact: true }).fill('data=合成v2\nstep=人工核对');
  await page.screenshot({ path: '../.cache/frontend-manual-question-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  const secondPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  const second: QuestionResult = await (await secondPromise).json();
  expect(bodies[1]).toMatchObject({ text: secondText, scope: { data: '合成v2', step: '人工核对' } });
  expect(bodies[1].project_id).not.toBe(bodies[0].project_id);
  const claim: Claim = (await (await request.get(`/api/claims/${second.claim_id}`, { headers })).json()).claim;
  expect(claim.payload.content).toBe(secondText);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: '关闭详情', exact: true }).click();
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: primary });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue(firstText);
  const firstPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  expect((await firstPromise).status()).toBe(200);
  expect(bodies[2].request_id).toBe(bodies[0].request_id);
  expect(bodies[2].project_id).toBe(bodies[0].project_id);
  const secondGraph: GraphData = await (await request.get(`/api/graph?project=${bodies[1].project_id}`, { headers })).json();
  expect(secondGraph.claims.some(item => item.payload.content === firstText)).toBe(false);
});

test('401后重新登录保留输入和意图，不自动提交', async ({ page }) => {
  const bodies: QuestionRequest[] = [];
  await page.route('**/api/records/question', async route => {
    bodies.push(route.request().postDataJSON());
    if (bodies.length === 1) await route.fulfill({ status: 401, json: { error: '合成人工记录令牌失效' } });
    else await route.continue();
  });
  let dialog = await openQuestion(page);
  const text = '合成重新鉴权后保留的问题';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(text);
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  await expect(page.getByRole('heading', { name: '打开你的研究决定史', exact: true })).toBeVisible();
  await page.getByLabel('访问令牌', { exact: true }).fill('synthetic-browser-token');
  await page.getByRole('button', { name: '进入本地工作区', exact: false }).click();
  dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue(text);
  await expect(dialog.getByRole('button', { name: '保存研究问题', exact: true })).toBeEnabled();
  expect(bodies).toHaveLength(1);
  const savedPromise = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  expect((await savedPromise).status()).toBe(200);
  expect(bodies[1].request_id).toBe(bodies[0].request_id);
  expect(bodies[1].project_id).toBe(bodies[0].project_id);
});

test('旧成功响应延迟到达时保留切换项目后的新草稿，正确保存新意图', async ({ page, request }) => {
  const bodies: QuestionRequest[] = [];
  const oldSaved: QuestionResult[] = [];
  let release!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/records/question', async route => {
    bodies.push(route.request().postDataJSON());
    const response = await route.fetch();
    if (bodies.length === 1) { oldSaved.push(await response.json()); await held; }
    await route.fulfill({ response });
  });
  let dialog = await openQuestion(page);
  const oldText = '合成延迟响应的旧人工问题';
  const newText = '合成切回项目后输入的新人工问题';
  const otherText = '合成另一项目尚未提交的草稿';
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(oldText);
  const oldResponse = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  await expect.poll(() => oldSaved.length).toBe(1);
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: secondary });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(otherText);
  await dialog.getByRole('button', { name: '关闭新增问题', exact: true }).click();
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: primary });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '新增研究问题', exact: true });
  await dialog.getByLabel('研究问题正文', { exact: true }).fill(newText);
  release();
  expect((await oldResponse).status()).toBe(200);
  await expect(dialog.getByLabel('研究问题正文', { exact: true })).toHaveValue(newText);
  await expect(dialog.getByRole('button', { name: '保存研究问题', exact: true })).toBeEnabled();
  await expect(page.getByRole('dialog', { name: `记录 ${oldSaved[0].claim_id} 详情`, exact: true })).toHaveCount(0);
  const savedResponse = page.waitForResponse(response => response.url().endsWith('/api/records/question'));
  await dialog.getByRole('button', { name: '保存研究问题', exact: true }).click();
  const saved: QuestionResult = await (await savedResponse).json();
  expect(bodies).toHaveLength(2);
  expect(bodies[1].request_id).not.toBe(bodies[0].request_id);
  expect(bodies[1].project_id).toBe(bodies[0].project_id);
  await expect(page.getByRole('dialog', { name: `记录 ${saved.claim_id} 详情`, exact: true })).toContainText(newText);
  const graph: GraphData = await (await request.get(`/api/graph?project=${bodies[0].project_id}`, { headers })).json();
  expect(graph.claims.filter(item => item.payload.content === oldText)).toHaveLength(1);
  expect(graph.claims.filter(item => item.payload.content === newText)).toHaveLength(1);
  await page.getByRole('button', { name: '关闭详情', exact: true }).click();
  await page.getByLabel('当前项目', { exact: true }).selectOption({ label: secondary });
  await page.getByRole('button', { name: '新增研究问题', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '新增研究问题', exact: true }).getByLabel('研究问题正文', { exact: true })).toHaveValue(otherText);
});
